### ISSUE TITLE
Publish This Week's IDEA #9 (continuity)

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-team#10]
This week, we’re exploring what it means to promote continuity. See the [draft gDoc](https://docs.google.com/document/d/1P9ddRnELWrAZlfuLjnFO_CvitGp5iJLLCUP2DHwdtSY/edit#) 🔒.

**Comment by afeijoo** [comment]
@thisisdano Ready for your review!

**Comment by thisisdano** [comment]
LGTM

**Comment by afeijoo** [comment]
Done in https://github.com/GSA/digitalgov.gov/pull/2632

https://digital.gov/2020/05/12/promote-continuity-better-support-customer-journeys/
