### ISSUE TITLE
Send out invites for spring 2020 meetup

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-team#11]
- [x] Confirm date (June 8 or 10?)
- [x] Finalize agenda
- [x] Confirm attendees and send invites
- [x] Draft pre-event questions
- [x] Draft invite text/email
- [x] Set up Eventbrite

**Comment by RhettSkelton** [comment]
Draft Emails for Your Review: https://docs.google.com/document/d/1I0HQzmXHz8xd2bshPBIBWqWyTzsG9Q0u9KjB_khqNgo/edit?ts=5eb9a9bf#
- [ ] Ammie Review
- [ ] Dan Review

Eventbrite Drafted: https://www.eventbrite.com/e/spring-2020-digital-experience-meetup-registration-104959919946
- [ ] Needs survey questions inputted (Ammie)
- [ ] Ammie Review
- [ ] Dan Review
- [ ] Platform details inputted (Gabby)
- [ ] Automated reminder emails setup (Gabby)

**Comment by afeijoo** [comment]
@thisisdano I did my review. Ready for you!

**Comment by thisisdano** [comment]
I've finished my review and edits of the email/eventbrite/questions. 🚀

**Comment by afeijoo** [comment]
Invite sent.
