### ISSUE TITLE
Create a quick briefing on the concept of Top Tasks

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#115]
Help the team understand the concept of Top Tasks by creating a quick briefing/presentation. Our goal is to understand how we can employ Top Tasks as a concept in our overall web strategy.

Predecessor to #1278.

**Comment by sofya-UX** [comment]
The deck has been created to support this issue and as a result of this research. It can be accessed [here](https://docs.google.com/presentation/d/1tfvpqFr_0U9QrAm26nnhR0PxPyrzDBO0LWt5IJFeZf0/edit?usp=sharing)
