### ISSUE TITLE
Create planning calendar for future Newsletter editions

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#117]
Create a [calendar](https://docs.google.com/spreadsheets/d/1cqA2ezb2yUNUQxFUquj4smrdjkFGSkkiQKf1O44WphU/edit#gid=0) to plan out the next 3-5 months of Newsletter content.

**Comment by KMullan944** [comment]
This is complete! reviewed with Dan, we are putting it into effect with the Dec'21 edition.
