### ISSUE TITLE
Update Designer GS Research Plan

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#135]
Update the Designer GS Research Plan in light of landscape analysis. Document questions we're going to ask in user interviews.

**Comment by sofya-UX** [comment]
Adding the link to the updated [Research Plan]🔒(https://docs.google.com/document/d/1RAp7nyAwZfMjNE9HMD9cM4nud6SL8avqzZZCYXTtWDw/edit#heading=h.t75l9lko3hoa)
