### ISSUE TITLE
First draft comms plan for 3.0 release

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#137]
In this first draft, we're looking to define:

-- Kinds of comms activities we need to be doing
-- Theme of comms
-- Channels

**Comment by bonnieAcameron** [comment]
First draft: 
[Comms Plan for USWDS 3.0](https://docs.google.com/document/d/1TE2D9wO4A3H0QV0D2sxiINvTKMAZx7wWpfmRB4kEAsw/edit#)
