### ISSUE TITLE
Draft social posts for Global Accessibility Awareness Day

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-team#16]
Global Accessibility Awareness Day (GAAD) is May 21. Draft some [social posts](https://docs.google.com/document/d/1PrRrG2am5dwtDfInal-uAE8p051_ZskKG6ksjunNlHw/edit):lock: on USWDS for GAAD.

**Comment by afeijoo** [comment]
I added some posts. @thisisdano take a look if you'd like.

**Comment by thisisdano** [comment]
These look good to me! :shipit:

**Comment by afeijoo** [comment]
Social posts are going out today on GSA and TTS channels. 

I also posted a note in #uswds-public Slack: https://gsa-tts.slack.com/archives/C3F14AHSQ/p1590081530431600
