### ISSUE TITLE
Draft June MC promos (social & Slack)

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#170]
Draft social and Slack promos https://docs.google.com/document/d/1VpFgCJWY_dsl7RBE3gdw33YoKQXog6addMTAcRczTvE/edit#

**Comment by bonnieAcameron** [comment]
Ready for review: https://docs.google.com/document/d/1VpFgCJWY_dsl7RBE3gdw33YoKQXog6addMTAcRczTvE/edit#heading=h.5jrcesdyaklo
