### ISSUE TITLE
Aug 22 MC Listserv Emails

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#191]
- [x] Draft emails
- [x] Send to Dan for approval
- [x] Decide on send date
- [x] Update [Monthly Call Schedule plan](https://docs.google.com/document/d/1Ogb3w0BxHxuBjeMBHXmIPpmUffZzk7vevx_R938J_Dg/edit#) with send date 
- [x] Send to Listservs
- [x] Remind Dan to send to Content Managers listserv

**Comment by thisisdano** [comment]
DONE
