### ISSUE TITLE
Aug 22 MC Event Brief Step 2

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#193]
- [x] Fill out [Step 2 of Event Brief](https://docs.google.com/document/d/1hCGDP3h9MQWN3IvSBLt5PPHrtr32r1dpsdxbN4yXAJc/edit)
- [x] Tag Dan for approval
- [x] Make any requested updates
- [x] Tag Jeannie/Laurie letting them know its complete

**Comment by thisisdano** [comment]
Done
