### ISSUE TITLE
Aug 22 MC Event Brief Step 1

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#194]
Event Brief: https://docs.google.com/document/d/1hCGDP3h9MQWN3IvSBLt5PPHrtr32r1dpsdxbN4yXAJc/edit

Schedule Plan: https://docs.google.com/document/d/1Ogb3w0BxHxuBjeMBHXmIPpmUffZzk7vevx_R938J_Dg/edit

**Comment by bonnieAcameron** [comment]
Updated, completion is dependent upon approval of the patterns team as speakers and the addition of their names to the document

**Comment by thisisdano** [comment]
Done
