### ISSUE TITLE
By Aug 8: Aug '22 Newsletter

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#197]
Draft and send the Aug '22 Newsletter. Goal to send by: Aug 8

**Comment by bonnieAcameron** [comment]
Draft: https://docs.google.com/document/d/1cR1fgq4afnGvJw7kD_mt9Hoey0RoCvwQYtCdrcHxekk/edit#heading=h.chsio4v8jwr3

**Comment by thisisdano** [comment]
SENT
