### ISSUE TITLE
Decide on ZenDesk signature

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#203]
What signature do we want to use in ZenDesk?

**Comment by brunerae** [comment]
@thisisdano  what about using our standard email one and then just leaving out the phone #/email bit maybe?

{Name}, Contractor
Bixal
Technology Transformation Services
U.S. General Services Administration

**Comment by thisisdano** [comment]
```
FirstName

[USWDS](http://designsystem.digital.gov/)
Technology Transformation Services
U.S. General Services Administration
[uswds@gsa.gov](uswds@gsa.gov)
```
