### ISSUE TITLE
Set-up Zendesk account (James)

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#204]
1. go to https://gsa-solutionshelp.zendesk.com/, click on I'm an agent and login using your GSA gmail connection. If it does not send you to GSA’s gmail SSO, let me know right away.
3. Everyone (after logging in) needs to click on the little person icon in the upper right corner (might be your photo if they still have it from before - mine was in there), and select View Profile
4. In the left-hand panel, enter your team’s signature block in the Signature field. Be sure to include your name, especially if you’re a person that doesn’t always type your name at the end of emails.

**Comment by mejiaj** [comment]
@brunerae I've logged in and added my signature.
