### ISSUE TITLE
Update forwarding rule for Google Group email

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#205]
it’s time to update the forwarding rule for delegated email addresses or add the ZD email address to your google group 

[uswds@gsa-solutionshelp.zendesk.com](mailto:uswds@gsa-solutionshelp.zendesk.com)

After you have done this, let Dawn McClesky know and she'll add your team’s address to the list of addresses ZD knows about. it will send a verification email to you, which we believe you don’t have to do anything about.

**Comment by thisisdano** [comment]
DONE
