### ISSUE TITLE
Set-up Macros in ZenDesk

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#206]
Set-up our old Macros in ZD https://docs.google.com/document/d/1dFdVNJoNSYUnxSzqGLkCaIOqWBkcIEnSVgx4A_MhLtg/edit#

**Comment by brunerae** [comment]
https://gsa-solutionshelp.zendesk.com/admin/workspaces/agent-workspace/macros?access=shared&active=true&page=1&per_page=100&sort_by=alphabetical

**Comment by thisisdano** [comment]
Done
