### ISSUE TITLE
This Week's IDEA: Build Sites to Address the Entire User Journey

### ISSUE THREAD

**Issue by RhettSkelton** [uswds/uswds-team#21]
Build Sites to Address the Entire User Journey
https://docs.google.com/document/d/1xp5eVLXWIUSEOzHdrPXYL4Jd7StWbLx_-w0yMRUnftM/edit#heading=h.uhqjgz9ylxby

**Comment by afeijoo** [comment]
The post was published today at https://digital.gov/2020/06/16/build-sites-address-entire-user-journey/

I shared on #uswds-public Slack: https://gsa-tts.slack.com/archives/C3F14AHSQ/p1592340422089500
