### ISSUE TITLE
Step 1 & 2 of Sep '22 Event Brief

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#213]
Fill out steps 1 and 2 of the [Event Brief.](https://docs.google.com/document/d/1SaMdczrKaWmlcdoAvLkFgJusqJSX7qGz0mEbIyE30o0/edit)

**Comment by brunerae** [comment]
Hi @thisisdano ! Both Steps 1 and 2 of the [Event Brief](https://docs.google.com/document/d/1SaMdczrKaWmlcdoAvLkFgJusqJSX7qGz0mEbIyE30o0/edit)are ready for your review.

**Step 1**
This is ready for your dated signature.

**Step 2**
This is ready for your review and pending signature once we finalize the speaker information. I am working with Jonah on that.

**Comment by thisisdano** [comment]
Done
