### ISSUE TITLE
Send by Sep 5: Sep '22 MC Listserv emails

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#216]
Draft emails for Listservs and send. Prep Content Mgrs. email for Dan to send.

https://docs.google.com/document/d/1dgYowtc0oYsF-Mn59qBZ83ZTpqtOr02mFhDiCtgBeBs/edit#

**Comment by brunerae** [comment]
Sent except for fed-only listserv; ready for your send-out @thisisdano !

**Comment by thisisdano** [comment]
Done
