### ISSUE TITLE
Send by Sep 8: Sep '22 Newsletter

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#217]
Write the Sep '22 Newsletter for review and approval by Dan. Send out by Sep 8.

**Comment by bonnieAcameron** [comment]
Link to newsletter copy https://docs.google.com/document/d/1d1-WprcEmhAuE_DQz5rcy_9xOzA-wxqyk9we8NhmXmQ/edit#

**Comment by thisisdano** [comment]
Done
