### ISSUE TITLE
Internal survey for Roadmapping goals (Oct-Jan)

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#218]
Send out survey to internal team to assess their viewpoint on painpoints/goals for next roamp.

**Comment by brunerae** [comment]
Survey results:https://docs.google.com/forms/d/1N2sJcO6z2u6tqyUun6OdCvtHIlGq2-ccxkBDAgZChPE/edit#responses

**Comment by thisisdano** [comment]
Done
