### ISSUE TITLE
Document "state of the practice" for UX research

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#220]
Let's document the current state of the UX practice. 

- What does our process look like?
- What tools do we use?
- What tools should we be using?
- What exists in our GDrive - let's record it somewhere so we have a full listing of all of the research we've completed

**Comment by jaclinec** [comment]
A draft of the USWDS Research Practice can be found here: https://docs.google.com/document/d/1kW_eRjQohx5bNuA_6Tt2xJxpUptaX7tO9aJAAoh09wI/edit?usp=sharing

It is still a work in progress and there are certain sections that are not fully filled out. The intention is that this will be a living document that will be edited over time, so it will evolve as the practice matures.

**Comment by mejiaj** [comment]
@jaclinec nice work! I like how the sections are broken out. There are also many useful links.

I've added some comments/questions based on some things I've found.
