### ISSUE TITLE
Set-up Component Acceptance Framework document

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#225]
Set-up a document that allows us to track our process for intaking new Features/Components. We'll use this to capture notes as we go through the Tabs component response.

**Comment by brunerae** [comment]
@thisisdano / @mejiaj / @amyleadem I've set up a document we can use to capture this process, https://docs.google.com/document/d/1Kq8N3SC9afR78KvCO6TprxfZC9w0C5zJSzOJAmSV9A0/edit#

**Comment by thisisdano** [comment]
Done
