### ISSUE TITLE
Answer ZD #1456

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#227]
https://gsa-solutionshelp.zendesk.com/agent/tickets/1456

**Comment by mejiaj** [comment]
Verified and responded with some links to documentation.

**Comment by brunerae** [comment]
hey @mejiaj ! Are you able to resend your response? I don't think ZD captured it. Thank you!!

**Comment by mejiaj** [comment]
@brunerae resent and added as an internal note (just in case). I had the ticket in `Pending` but it's been a week and we haven't heard back.

Should I close the ticket?

**Comment by thisisdano** [comment]
Yeah, let's close
