### ISSUE TITLE
Post by Oct 14: Oct '22 MC Promos

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#229]
Draft and send promo content for approval. Post to Twitter & Slack.

- [x] Draft
- [ ] Approve
- [ ] Event page link format
- [ ] Send

**Comment by bonnieAcameron** [comment]
Draft: https://docs.google.com/document/d/1C0GnEI86G4prNgO18q3m9SWTtZOzqDxojokC0u4TkC4/edit#
