### ISSUE TITLE
Move from `master` branch to `main` across USWDS repos

### ISSUE THREAD

**Issue by thisisdano** [uswds/uswds-team#23]
For each of our repos, we should move from using a `master` branch to a `main` branch. This in line with [what GitHub is doing](https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/) and it's a small but meaningful step toward promoting inclusive language in our project and codebase.

We'll need to update not only our branches, but our documentation and codebase hooks — particularly with CI.

We can start with the instructions [here](https://www.hanselman.com/blog/EasilyRenameYourGitDefaultBranchFromMasterToMain.aspx) in one of our smaller repos, and apply what we learned to the larger ones.

Are there any other downstream implications to this change?

- [x] `uswds`
- [x] `uswds-gulp`
- [x] `uswds-sandbox`
- [x] `uswds-site`
- [x] `uswds-team`
- [x] `uswds-for-designers`
- [x] `luminance-tool`
- [x] `public-sans`

**Comment by thisisdano** [comment]
Blocked on the `uswds` repo until we can double-check any existing references to the `master` branch

**Comment by brunerae** [comment]
@thisisdano this can be closed
