### ISSUE TITLE
Send by Oct 14: Oct '22 MC Listserv emails

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#230]
Draft emails for Listservs. Send all but content managers - tag Dan for sending.

- [x] Draft
- [x] Approve
- [x] Format and add event link
- [x] Send

**Comment by bonnieAcameron** [comment]
Draft: https://docs.google.com/document/d/1C0GnEI86G4prNgO18q3m9SWTtZOzqDxojokC0u4TkC4/edit#
