### ISSUE TITLE
Test an improvement/post on the News & Updates section of designsystem.digital.gov

### ISSUE THREAD

**Issue by RhettSkelton** [uswds/uswds-team#24]
Use the monthly call to update various sections of designsystem.digital.gov. Below is a link to a few options for how we might update some of the pages/content based on the June Monthly call.
https://docs.google.com/document/d/15lXC8nIfPwAXdr-Wzp7XNxDJEhPysBV699vKPgA7fyI/edit#

**Comment by RhettSkelton** [comment]
@saracope offered these JSON options for pulling in content from Digital.gov.

Topics: https://digital.gov/topics/v1/json/
Blog posts: https://digital.gov/news/index.json
Events: https://digital.gov/events/index.json
Individual Event posts: 
https://digital.gov/2018/07/17/experiments-in-tweaking-agile-for-ux/index.json
https://digital.gov/event/2018/07/26/civic-service-design-tools-tactics/index.json

Just dropping them here for reference. The API is still 1-2 months out.

**Comment by RhettSkelton** [comment]
- [ ] Review the documentation (@katieekline )
- [ ] Come up with an initial step to improve the News & Update section
- [ ] Draft new issues based on next steps.

**Comment by afeijoo** [comment]
LGTM. I left two comments open in the lifecycle plan, so we can address them as we do them for the next feature.
