### ISSUE TITLE
Work on IAAF presentation slides

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#267]

**Comment by jaclinec** [comment]
We created a [draft of the script](https://docs.google.com/document/d/19W0hXHt5ccnMvOg_dOqZBbYk6_rMiTS34DFZOg4iVb4/edit?usp=sharing) and the slides

[IAAF 2023 Presentation DRAFT.pptx](https://github.com/uswds/uswds-team/files/12751496/IAAF.2023.Presentation.DRAFT.pptx)

and sent them to Dan yesterday. They are still a work in progress, and we will likely need to request an extension on the deadline (which is Sep 29th) to submit. The 3 of us will continue to develop and refine the script and presentation, aiming to complete it as soon as possible.

**Comment by brunerae** [comment]
Closing as complete.
