### ISSUE TITLE
Create presentation for usability testing round 1 findings

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#270]

**Comment by jaclinec** [comment]
[Draft of presentation here](https://docs.google.com/presentation/d/1C_tOmXqyO6zQ81cgFnfnzIZR_7NxQnkS0hTjGx8apso/edit?usp=sharing). I expect to finish creating it by early next week, and hope to present it to the core team by mid-next week.

**Comment by jaclinec** [comment]
The slide deck is complete and I used it to present usability test findings to the core team yesterday.

**Comment by thisisdano** [comment]
DOne
