### ISSUE TITLE
Create documentation outlining steps to take for day of usability testing

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#272]
We are documenting our process for planning and carrying out usability testing with users with disabilities. We already have several process documents:

- High level usability testing workflow
- General best practices for testing with people with disabilities
- Outreach and communications plan for recruiting

This Github issue is to document my creating a practical [step-by-step checklist for what to do on testing day](https://docs.google.com/document/d/1Vn4X7HBPiis476P6ctabPS5MOR34gWGpuJNko6JhsU8/edit?usp=sharing). It will be linked to the '[High level usability testing workflow](https://docs.google.com/document/d/16IyT85PVC7YW7UBJBtK0AXsMdwbrEHKo1wyg_BUE-Mg/edit?usp=sharing)' document in the first bullet above.

**Comment by jaclinec** [comment]
I finished creating the '[Testing Day Checklist](https://docs.google.com/document/d/1Vn4X7HBPiis476P6ctabPS5MOR34gWGpuJNko6JhsU8/edit?usp=sharing)' and its ready for fed final review.

**Comment by annepetersen** [comment]
Made a few edits, but otherwise looks good to me

**Comment by thisisdano** [comment]
Done!
