### ISSUE TITLE
January 2024 USWDS Newsletter

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-team#276]

**Comment by finekatie** [comment]
This is a ticket to outline the work of drafting and sending the December 2023 USWDS newsletter. We are aiming to send the newsletter on Monday, January ___

Helpful links:

[Newsletter folder in Google Drive](https://drive.google.com/drive/folders/1xq1tcxcV5hZxNA-6_PH8pycQkkbrCXJ6)
[November newsletter draft here](https://docs.google.com/document/d/16PFglvQnkv2c4GN7nwTjBO_EyhSOfbCuz5rCcgLJs6g/edit)

[GovDelivery](https://admin.govdelivery.com/session/new)

Steps to send newsletter
Draft copy

- [ ]  3.7.1 release (out by 12/8?)
- [ ]  https://github.com/uswds/uswds-compile/pull/83
- [ ]  New USWDS sites (if applicable)
- [ ]  Accessibility feature on usability research with participants with disabilities
- [ ]  New research page
- [ ]  Monthly call recordings page and note about no monthly call in Dec.
- [ ]  November monthly call recap

Review

 

- [ ] Review by content team
- [ ]  Review and feedback from larger team if needed
- [ ]  Approval by Anne and Dan

Compile

 

- [ ] Add content to GovDelivery
- [ ]  Proofread
- [ ]  Publish

**Comment by finekatie** [comment]
About 65% finished. Still waiting for monthly call promo copy and link to page. Once that copy goes up and Monthly Call page goes up, Accessibility Discussion will also go live and we'll link to that. This still needs some team and fed review once all that's done. Expecting to launch on or around Weds 1/10

**Comment by sarah-sch** [comment]
1/8 update - waiting for full approval of event copy and publication of event page to finish draft. In touch with Jeannie about progress.

**Comment by finekatie** [comment]
This is ready for fed review, then publish.

**Comment by finekatie** [comment]
1/12 This is still in review with Dan.

**Comment by finekatie** [comment]
We got approval from Dan on 1/16 and published. This is done.
