### ISSUE TITLE
March 2024 USWDS Newsletter

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-team#278]
Overview
This is a ticket to outline the work of drafting and sending the March 2024 USWDS newsletter. We are aiming to send the newsletter on Monday, March 11, 2024.

Helpful links:
[March newsletter here](https://docs.google.com/document/d/1PGFh4hGC3ZVM8zrF3dwH9cfpNapH223jrSNITSzrW9I/edit)
[Newsletter folder in Google Drive](https://drive.google.com/drive/folders/1xq1tcxcV5hZxNA-6_PH8pycQkkbrCXJ6)
[GovDelivery](https://admin.govdelivery.com/session/new)

## Steps to send newsletter
Draft copy
- [x]  New releases?
- [x]  New USWDS sites
- [x]  Accessibility feature 
- [x]  March monthly call
- [x]  Feb. monthly call recap
- [x] Federal employees research recruitment

Review
- [x]  Review by content team
- [x]  Review and feedback from larger team if needed
- [x]  Approval by Anne and Dan

Compile

- [x]  Add content to GovDelivery
- [x]  Proofread
- [x]  Publish

**Comment by finekatie** [comment]
Started draft today [here](https://docs.google.com/document/d/1PGFh4hGC3ZVM8zrF3dwH9cfpNapH223jrSNITSzrW9I/edit)

**Comment by sarah-sch** [comment]
Accessibility feature and newsletter copy sent for fed final review week of 3/4-3/8

**Comment by thisisdano** [comment]
Approved copy

**Comment by finekatie** [comment]
Newsletter proofed, edited for links, etc. and sent. This is complete.
