### ISSUE TITLE
April 2024 USWDS Newsletter

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-team#279]
Overview
This is a ticket to outline the work of drafting and sending the April 2024 USWDS newsletter. We are aiming to send the newsletter on Wednesday, April 10, 2024.

Helpful links:
[April newsletter here](https://docs.google.com/document/d/1Jf-xM2_24WAC-cFJRgvOYWTBwzPXNdhE3modl8Uty3I/edit?usp=sharing)
[Newsletter folder in Google Drive](https://drive.google.com/drive/folders/1xq1tcxcV5hZxNA-6_PH8pycQkkbrCXJ6)
[GovDelivery](https://admin.govdelivery.com/session/new)

Steps to send newsletter
Draft copy
- [x] New releases? - no new release to feature this month
- [x] New USWDS sites?
- [x] [Accessibility feature](https://docs.google.com/document/d/1oOCL0IGhoCoU3A_27I4a8gXCS0ou81xbk2ww1nFErzk/edit?usp=sharing) - approved by Anne before they left for PTO. With Dan.
- [x] Featured component discussions
- [x] April monthly call
- [x] March monthly call recap
- [x] Federal employees research recruitment?

Review
- [x]  Review by content team
- [x]  Review and feedback from larger team if needed
- [x]  Approval by Anne and Dan

Compile
- [x]  Add content to GovDelivery
- [x]  Proofread
- [x]  Publish

**Comment by sarah-sch** [comment]
3/22/2024 - updated issue and [created draft of April newsletter](https://docs.google.com/document/d/1Jf-xM2_24WAC-cFJRgvOYWTBwzPXNdhE3modl8Uty3I/edit?usp=sharing)

**Comment by sarah-sch** [comment]
3/25 - met with @amycole501 and @alex-hull to address accessibility discussion for April newsletter. Discussion will touch on simple forms, PDF, and how stress (combined with specific disabilities) can make it difficult to fill out forms, especially during crises and life transitions.

**Comment by sarah-sch** [comment]
4/8 - Passed draft to @finekatie to review. Content is mostly done. Still waiting on link to accessibility discussion and final April MC text.

**Comment by finekatie** [comment]
Still waiting for FFR.

**Comment by finekatie** [comment]
Got FFR today and we updated and published - scheduled for 4/16 915am EDT.
