### ISSUE TITLE
May 2024 USWDS Newsletter

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-team#280]
Helpful links:
[May newsletter here](https://docs.google.com/document/d/1fbMXG3jznU8qkuV39tVVaBtfV0gRTQrih3hj59Q4V3c)
[Newsletter folder in Google Drive](https://drive.google.com/drive/folders/1xq1tcxcV5hZxNA-6_PH8pycQkkbrCXJ6)
[GovDelivery](https://admin.govdelivery.com/session/new)

## Steps to send newsletter
**Draft copy**

 

- [x] New releases  - 3.8.1 - Katie asked dev team for copy 5/3
- [x] New USWDS sites - https://beta.notify.gov/ - holding off for now due to length
- [x] Accessibility feature - digital accessibility and voting (to align with monthly call) - in review
- [x] Featured component discussions
- [x] Suggest a topic for August monthly call (GitHub discussion?) - Sarah drafted 5/6
- [x] May monthly call
- [x] April monthly call recap
- [x]  Federal employees research recruitment?
- [x] Patterns pages? - push to another month due to length

**Review**

 

- [x] Review by content team
- [x] Review and feedback from larger team if needed
- [x] Approval by Anne and Dan

**Compile**

 

- [x] Add content to GovDelivery
- [x]  Proofread
- [x]  Publish

**Comment by finekatie** [comment]
draft started 4/25: https://docs.google.com/document/d/1fbMXG3jznU8qkuV39tVVaBtfV0gRTQrih3hj59Q4V3c

**Comment by sarah-sch** [comment]
@finekatie - Adding in item for soliciting topic ideas for the August monthly call (the topic is going to be "community choice"). I discussed with @annepetersen and @thisisdano yesterday that we should consider a GitHub discussion featured in the May newsletter to get the conversation started. Maybe we can ask folks to vote in the June newsletter. We may have time to discuss with broader team at CS/UX/a11y sync this afternoon.

**Comment by finekatie** [comment]
reviewing May a11y discussion content

**Comment by finekatie** [comment]
requested release notes from Dev today

**Comment by sarah-sch** [comment]
5/6 - drafted [copy for the August MC discussion](https://docs.google.com/document/d/1IzEqoW522n5sxiz-eACtqUoGw4Eoqfu8CIkXF2FFvj8/edit?usp=sharing) and passing to @finekatie for review. Will review newsletter copy today as well.

**Comment by sarah-sch** [comment]
5/10 - made updates based on edits to accessibility discussion and Aug. monthly call discussion. Submitting for fed final review.

**Comment by finekatie** [comment]
A11y discussion, April Q&A and August MC discussions are all up on GH. Links in newsletter.
