### ISSUE TITLE
Draft November monthly call script & slides

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#292]
[November MC script for Jacline's section here](https://docs.google.com/document/d/1x6I-AtqYDWcnTVKGRnyCKutVPnbnUVuEtISuqrB9WSo/edit?usp=sharing). Still a work in progress.

**Comment by jaclinec** [comment]
In fairly good 'first draft' shape - I wrote script content for everything I plan to cover. I will work on refining it early in the week of Nov MC when I return (will mostly be OOO for the next week).

**Comment by mejiaj** [comment]
@jaclinec @cory-churches @sarah-sch would it help if we broke these out into smaller tasks in the future? It could help improve tracking and splitting responsibilities.

**Example**

- [ ] Monthly Call
  - [ ] Choose theme
  - [ ] Write event brief
  - [ ] Create outline
  - [ ] Create script
  - [ ] Create slides
  - [ ] Dress rehearsal
  - [ ] Revisions
  - [ ] Upload slides to DigitalGov

**Comment by jaclinec** [comment]
If it makes sense to track all the tasks for MC within 1 issue, then having a checklist of the tasks within that issue would be helpful. But I wonder how assigning to people works...many of us are working on these tasks simultaneously. And 'choosing theme' sometimes happens far in advance. 

This issue was originally written just for my drafting my part of the script. Can we have separate issues but add the Monthly Call tag and the relevant monthly milestone, or is that too scattered?

**Comment by mejiaj** [comment]
@jaclinec we can convert the task items into their own issues easily[^1] once the task list is created. 

<img width="858" alt="Screenshot 2023-11-06 at 5 40 07 PM" src="https://github.com/uswds/uswds-team/assets/3385219/68052120-f70e-43cf-9fb6-54d0af952393">

[^1]: https://docs.github.com/en/issues/managing-your-tasks-with-tasklists/managing-tasks-in-a-tasklist#converting-draft-tasks-to-issues-in-a-tasklist

**Comment by brunerae** [comment]
Closing as complete
