### ISSUE TITLE
Add "Testing Day Checklist" to the Github wiki

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#293]
In the course of carrying out usability testing for components in Q3 2023, we created a "Testing Day Checklist" to serve as a tool to help streamline routine testing day procedures. We decided it'd be helpful to offer a version of this checklist to the USWDS community. We decided to publish this checklist in the uswds Github Wiki,

**Comment by jaclinec** [comment]
The [Usability Testing Day Checklist wiki page](https://github.com/uswds/uswds/wiki/Usability-Testing-Day-Checklist) is now published, but I'd like for Content Strategy (@sarah-sch , @katieekline )to take a look at the [drafted content](https://docs.google.com/document/d/1zV0KsLiJDhKfXqREGhbwrL3UQO_LaZS7EV3HgvTlH_4/edit?usp=sharing) and add comments/edits. I can update the wiki page based on their recommendations.

**Comment by brunerae** [comment]
Closing as complete.
