### ISSUE TITLE
Editorial Calendar: Documenting process for Monthly Call and other communications

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds-team#298]
Add information to [Editorial Calendar sheet](https://docs.google.com/spreadsheets/d/1uE7G0JarVqrwaaQQO9gWV2ywWmXJUj_AVwYO9BMQHxM/edit#gid=861982751) to better document process for and generally share timelines for Monthly Call comms around events, along with any other comms work we do.

**Comment by finekatie** [comment]
Starting this now, but it will span over another sprint at least.

**Comment by brunerae** [comment]
This Issue was for our 2023 Editorial Calendar. I am closing it as no longer relevant.
