### ISSUE TITLE
Operationalize Usability Research: Consider how to keep moving component updates and usability testing forward

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#299]
In the spirit of doing repeatable, ongoing usability testing on components, we need to:

- Determine the cadence and approach to testing new components and validating previously tested components.
- Establish a system that ensures the most pressing issues from test findings are prioritized in dev issue triage meetings and worked on so we can keep making improvements and have momentum for ongoing/validation component usability testing.
- Decide which components we'd like to test in the first half of next year. We'll get together for a prioritization workshop - the goal is to prioritize and decide on the next 2 batches of components to test (10-12 components total).

Tasks:

- [x] Determine cadence for usability testing new and previously tested batches of components
- [x] Check that all findings from last round of testing have issues and that they have proper metadata
- [x] Establish process to prioritize issues from usability test findings
- [x] Create and run a component testing prioritization workshop for Q1&2 2024 testing

**Comment by jaclinec** [comment]
See the [structure outline of the workshop](https://docs.google.com/document/d/1mElx0JfsrDqyzFEjTSe1nqnIBI2azjqsYcdH4ACejSc/edit?usp=sharing).

[Mural board](https://app.mural.co/t/gsa6/m/gsa6/1698937522390/9b1ad3741f4656f41ccf4eaf8075c69a5816c1a1?sender=u83d0e400125d69b595f75755).

**Comment by jaclinec** [comment]
Proposal for component testing cadence and approach:

- Test 1 NEW batch of components each quarter
- Aim to conduct validation testing for “previously tested” components each quarter
- Total = 2 rounds of testing for different batches of components per quarter

It takes time to implement recommended changes/improvements to components after testing. This system allows us to continue to move forward on testing new batches of components, and then validating previously tested batches whenever they are ready. How long it takes between the initial test and the validation test after improvements are made depends on the complexity of the solutions and the team's bandwidth to work on improvements.

I'm also suggesting we "name" each batch of components we test so it is easier to talk about them with the team. For instance, the first batch of components could be the "Buffalo" batch, the next could be "Zebra," then "Tiger" and so on. It's not completely necessary, but could be helpful in quickly and uniquely identifying a batch of components.

**Comment by jaclinec** [comment]
Re: establishing a process to prioritize issues from usability test findings, we discussed this at office hours yesterday. We agreed that we need to come up with a process that alerts devs to high priority work that relates to usability testing (as well as a11y audit red flags and content audit work).

In the meantime, we'll be sure to communicate with each other about priorities. Jacline/the researcher will assign a weight to issues from testing and separately alert devs to what should be a priority, either in an office hours, through internal communication before a triage meeting, and/or in PI planning so devs understand where to devote their time. Then, high priority items can get assigned and moved into sprints.

Additionally, we'd like to come up with an MVP for an improved label system.

**Comment by thisisdano** [comment]
Done
