### ISSUE TITLE
December Newsletter

### ISSUE THREAD

**Issue by sarah-sch** [uswds/uswds-team#304]
This is a ticket to outline the work of drafting and sending the December 2023 USWDS newsletter. We are aiming to send the newsletter on Monday, December 11.

Helpful links:

[Newsletter folder in Google Drive](https://drive.google.com/drive/folders/1xq1tcxcV5hZxNA-6_PH8pycQkkbrCXJ6)
[November newsletter draft here](https://docs.google.com/document/d/16PFglvQnkv2c4GN7nwTjBO_EyhSOfbCuz5rCcgLJs6g/edit)

[GovDelivery](https://admin.govdelivery.com/session/new)

### Steps to send newsletter

Draft copy
- [x] 3.7.1 release (out by 12/8?)
- [x] [USWDS Compile 1.1.0](https://github.com/uswds/uswds-compile/pull/83)
- [ ] New USWDS sites (if applicable)
- [x] Accessibility feature on usability research with participants with disabilities
- [x] New research page
- [x] Monthly call recordings page and note about no monthly call in Dec.
- [x] November monthly call recap

Review
- [x] Review by content team
- [x] Review and feedback from larger team if needed
- [x] Approval by Anne and Dan

Compile
- [x] Add content to GovDelivery
- [x] Proofread
- [x] Publish

**Comment by finekatie** [comment]
Sarah wrapped all this up yesterday and published. This is complete!
