### ISSUE TITLE
Confirm if there's a group already working on web components.

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-team#305]
Confirm If there's something already planned for another group (like 10X) that has this on their roadmap.

**Comment by annepetersen** [comment]
Recently learned that the answer on 10x, at least, is currently no (despite rumors to the contrary), but we're investigating a proposal. More to come there

**Comment by mejiaj** [comment]
Closing since there's no 10x team actively working on this. Interested in hearing how this affects our work.
