### ISSUE TITLE
Create participant consent form for critical checklists usability test

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#315]
We are doing usability testing for a critical accessibility checklist prototype, starting with the accordion. We need to send participants a consent form that they fill out before the session. The consent form gives them important information about the study and asks for permission to record the session.

**Comment by jaclinec** [comment]
[Google form preview.](https://docs.google.com/forms/d/e/1FAIpQLScDWH-BT6GOoDrV7j-YIqK6bQzsQD1m8TXvzpMvaC03yTQrZA/viewform)

For any participants that cannot use Google products, we will also have a Word doc version we can send. For anyone who gets the word doc, I'll ask them to respond to my email with a statement like: 

"I have read the USWDS Participation Consent form and understand the purpose of the study, that my participation is voluntary and I can withdraw at any time, that the session will be recorded, and that I will not be compensated for the session. I certify that I have read and understand the terms of participation and I agree to participate in this study."

**Comment by annepetersen** [comment]
Mine if I make some edits?

**Comment by jaclinec** [comment]
I don't mind if you edit, but it's important to note that I have already sent this to 3 participants. It's repurposed from the content testing study we did, so it was previously approved but I welcome making it better. I don't see a problem editing as long as it doesn't change the meaning of any content since folks have already filled it out and submitted it.

**Comment by annepetersen** [comment]
Revised; thanks! Also, could you link me to the content testing study in question?

**Comment by jaclinec** [comment]
Thanks! And sure, here's the [folder with all the content testing artifacts](https://drive.google.com/drive/folders/1pymM2yNpHKhIO5fTk4jEiISbIKSn4AMi?usp=sharing).
