### ISSUE TITLE
Update documentation for editing site

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-team#319]
Update [gDoc 🔒](https://docs.google.com/document/d/14dUu6qd9STeUfSQj_LO4xVeLywJiU42gS3LxPI3hIZs/edit#heading=h.l8zx00klvri0) for editing content on site.

**Comment by brunerae** [comment]
@sarah-sch / @finekatie were there specific updates we wanted to capture in this Issue? How can we close this?

**Comment by finekatie** [comment]
> @sarah-sch / @finekatie were there specific updates we wanted to capture in this Issue? How can we close this?

I have content [in this doc ](https://docs.google.com/document/d/1hxM1LFmTtuA33QCxJwQJo8r9yq6a0w6wu_khLZAGpTc)about creating PRs and Branches, but I'm not sure what we wanted to capture in the doc James mentioned above. This seems like a discussion to revisit. Perhaps close this issue and start a new one?

**Comment by finekatie** [comment]
Thanks @mejiaj , let me know if you want to collab at all.

**Comment by mejiaj** [comment]
I've updated the content in the doc to reflect the task of updating component a11y guidance(uswds/uswds-site#2840).

Edits/suggestions/comments in doc are welcome. If there are additional site update tasks that you'd like to see, please create a new issue or request them in the document.
