### ISSUE TITLE
Icons: Conduct literature review about icons' purposes and how it intersects with screen readers

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#335]
During planning for [zebra batch component testing](https://github.com/uswds/uswds-team/issues/322) (which includes testing the icon component), some questions cropped up about icons that we want to look into:

1. What is the distinction between an icon functioning as an icon and an icon functioning as a descriptive image? What makes an icon an icon versus an illustration/clip art? Functional vs illustrative
2. Should icons be perceivable to screen reader users when accompanied by text or should they remain hidden? 
               - Do icons have their own intrinsic meaning or value even when accompanied by text?

To explore answers to these questions, we're conducting a literature review.

**Comment by jaclinec** [comment]
Here is the [work-in-progress icons literature review.](https://docs.google.com/document/d/1zkIOs0KnAUSsWXNoe_tJ9m9KCCDh2r5ZxgMZWbVxW7g/edit?usp=sharing)

**Comment by jaclinec** [comment]
I finalized the [icons literature review](https://docs.google.com/document/d/1zkIOs0KnAUSsWXNoe_tJ9m9KCCDh2r5ZxgMZWbVxW7g/edit?usp=sharing) and so far have presented it and discussed it with Dan. The actual literature review and report meant for the internal team is done. 

Next steps:

- Present this research to Anne and the rest of the team
- Draft updated icons guidance where needed and have that reviewed by CS and then put on the site
- Consider publishing this literature review in a public forum (i.e. the Github wiki)

**Comment by jaclinec** [comment]
Also created a Google slide presentation: https://docs.google.com/presentation/d/1qFEFBA7RnHUszdwzW3mgqI2HVQYlqCfpOoUXJzMdS_o/edit?usp=sharing

**Comment by thisisdano** [comment]
Done
