### ISSUE TITLE
Draft content for invitation blast across channels to recruit fed user panel for research

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#337]
In an effort to keep building our usability research panel of federal employees, we will send out invitations across different channels for feds to sign up to participate. 

- [x] define channels to send invitations and draft outreach communications for each channel
- [ ] finalize outreach communications

**Comment by jaclinec** [comment]
Started [outreach communications draft.](https://docs.google.com/document/d/1OkC7WxM8XxegAhQ1W0MoT9HdHk9V2o20NCC8a4OS6T4/edit?usp=sharing)

**Comment by jaclinec** [comment]
@sarah-sch and @finekatie the draft of [outreach communications](https://docs.google.com/document/d/1OkC7WxM8XxegAhQ1W0MoT9HdHk9V2o20NCC8a4OS6T4/edit?usp=sharing) for building our federal user panel for research is ready for your review.

**Comment by finekatie** [comment]
Added a ton of comments and notes to the doc.

**Comment by finekatie** [comment]
Sarah and I are done review.

**Comment by sarah-sch** [comment]
@jaclinec - providing [suggestions per Anne's feedback](https://docs.google.com/document/d/1OkC7WxM8XxegAhQ1W0MoT9HdHk9V2o20NCC8a4OS6T4/edit?usp=sharing) on 3/5/2024

**Comment by jaclinec** [comment]
@annepetersen, this is ready for your review.

**Comment by annepetersen** [comment]
Approved!
