### ISSUE TITLE
Combobox landscape analysis

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#338]
We're doing a light landscape analysis to see how other design systems have implemented the search / result matching function of a combo box. This is in response to [results from usability testing](https://github.com/uswds/uswds/issues/5647) that found that the combo box search results do not match user expectations. I'm looking for possible solutions.

**Comment by jaclinec** [comment]
Draft of [combo box landscape analysis](https://docs.google.com/document/d/1JfsnjWjIfbrKVB7JN9OsRcJXg306b7JX8xTTHf_MD_I/edit?usp=sharing)

**Comment by thisisdano** [comment]
Done
