### ISSUE TITLE
Add Feb MC Q&A to Discussions

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#339]
Add [questions from the Monthly Call](https://docs.google.com/spreadsheets/d/1qLr8JzIbnVjqa44Rki8nVr4--Ls9G7TYvU3VT2ymrXk/edit#gid=0) to a Discussion post.

**Comment by sarah-sch** [comment]
Shared with @annepetersen and @thisisdano for preliminary feedback 3/8. After feedback, content team will clean up for fed final review. cc @finekatie

**Comment by sarah-sch** [comment]
Sharing [Q&A draft document](https://docs.google.com/document/d/1SZZF-AE-bENVMFWmECnKXfzPsVEaXJYwe9L8f2kaRbk/edit?usp=sharing) here for easier reference. CC @finekatie

**Comment by sarah-sch** [comment]
@annepetersen and @thisisdano - have accepted changes to [the Q&A document](https://docs.google.com/document/d/1SZZF-AE-bENVMFWmECnKXfzPsVEaXJYwe9L8f2kaRbk/edit?usp=sharing) and am sharing for fed final review. Thank you! cc @finekatie

**Comment by thisisdano** [comment]
This are OK to post to discussions.

**Comment by sarah-sch** [comment]
Thanks, @thisisdano and @annepetersen!
