### ISSUE TITLE
Audit GitHub labels & fields and propose improvements

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#342]
Let's review our GitHub labels and fields and identify opportunities for improvement. We'll use this to ensure we've also documented our project and repo metadata. Repos to review/document:

- [x] uswds/uswds
- [x] uswds/uswds-site
- [x] uswds/uswds-team
- [x] uswds/uswds-compile

We should ensure labels are:

- The same across all repos
- Accurately described in the `label description`
- Still in-use (delete if not being used)
- Not duplicative of other information in other metadata fields
- Not better suited as a standalone field

Once Labels are updated, we should:

- [ ] #343

**Comment by brunerae** [comment]
I've [documented all of our labels](https://docs.google.com/spreadsheets/d/1y0Cfn2_gCbA9ZxgH8uRPdUXCjc3egRNUVit_WX7nuRg/edit#gid=0) (GDrive 🔒) across:

- [ ] uswds/uswds
- [ ] uswds/uswds-site
- [ ] uswds/uswds-compile
- [ ] uswds/uswds-team

Next steps:

- [ ] Identify ones that may be better as a field
- [ ] Identify ones for deletion
- [ ] Identify ones we need to bring across other repos

**Comment by brunerae** [comment]
Hi @thisisdano - I've proposed some updates to our GitHub labels and fields. You can review my proposed changes [in the GSheet](https://docs.google.com/spreadsheets/d/1y0Cfn2_gCbA9ZxgH8uRPdUXCjc3egRNUVit_WX7nuRg/edit#gid=1625175603) [🔒]. If you're onboard with these changes, I'll update across repos and in our project.

**Comment by thisisdano** [comment]
Let's update everything across repos
