### ISSUE TITLE
FY24 Q2 Web Governance Policy Review

### ISSUE THREAD

**Issue by brunerae** [uswds/uswds-team#346]
The new TTS web content review policy requires all TTS website managers to:

- Review the content covered under the policy
- Identify necessary updates
- Work with their team to make those updates
- Complete the [Quarterly TTS web content review form](https://docs.google.com/forms/d/e/1FAIpQLSeN2Yfwqz9bG5dRIJ2i0ZxEhWF0wSdfs-KkdYb7t4cSY6ZJ0w/viewform) to validate that you have completed your review.

**Note:** This version of the policy only applies to targeted content areas. See the policy outline for more on the types of content that are and are not covered.

For additional information on the policy, see the [deck presented to the TTS Digital Council](https://docs.google.com/presentation/d/1H5wO0KoWqYAKfrgmNoUDNA8vUjRzT3eyE4ctuy1G-pw/edit#slide=id.g1ee04787bec_0_315) on January 8, 2024.

**Comment by brunerae** [comment]
Pulled together a [spreadsheet](https://docs.google.com/spreadsheets/d/1KPPHXr5YhV2Zyl-c9fZh6NB-kKgXyzgBZyIhio-97OA/edit?usp=sharing) (based on digital.gov's template) to track this and organize our response.

**Comment by brunerae** [comment]
Hi @annepetersen, this is ready for your review and final submission.

[Spreadsheet tracker](https://docs.google.com/spreadsheets/d/1KPPHXr5YhV2Zyl-c9fZh6NB-kKgXyzgBZyIhio-97OA/edit#gid=0) [GDrive🔒]

**Comment by annepetersen** [comment]
Submitted: thanks!
