### ISSUE TITLE
POAM - April '24

### ISSUE THREAD

**Issue by mejiaj** [uswds/uswds-team#348]
# Summary

POAM  updates for April 2024

- [ ] https://github.com/uswds/uswds/pull/5854
- [ ] https://github.com/uswds/uswds-site/pull/2448
- [ ] https://github.com/uswds/uswds-site/pull/2606
- [ ] https://github.com/uswds/uswds-sandbox/pull/132
- [ ] https://github.com/uswds/uswds-compile/pull/97
- [ ] https://github.com/uswds/uswds-tutorial/pull/46
- [ ] https://github.com/uswds/public-sans/pull/297

**Comment by thisisdano** [comment]
All done!
