### ISSUE TITLE
Submit a pitch for UXPA Magazine by Aug 15

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-team#36]
The upcoming 20.3 issue of UXPA Magazine will cover UX governance:

When designing experiences for our users, different disciplines merge into the equation. IT infrastructure, APIs, Data structures, Design Systems,  Open and Dynamic repositories for continuous improvement, to name a few, come into our mind. We need to synchronize all of them building a governance framework that puts users in the center of the system. All of those who want to write about the topic are welcome to submit. We are looking for articles that cover the topic from different perspectives and disciplines.

Article proposals are due August 15, 2020. Visit http://uxpamagazine.org/information-for-authors/ for information on how to submit submittal.

**Comment by katieekline** [comment]
@thisisdano and @afeijoo The [draft submission](https://docs.google.com/document/d/1eY9ydHMwopPTqnPlplYmQO62Xwzxh4BBGUJWBqMqTp8/edit?usp=sharing) is ready for your review.

**Comment by afeijoo** [comment]
@katieekline I suggested a few copy edits.

@thisisdano The [draft submission](https://docs.google.com/document/d/1eY9ydHMwopPTqnPlplYmQO62Xwzxh4BBGUJWBqMqTp8/edit?usp=sharing) is ready for your review. We need to submit it by COB tomorrow.

**Comment by afeijoo** [comment]
Emailed our pitch/proposal to uxmagazine at uxpa dot org.

**Comment by jAigret-Bix** [comment]
[Submitted Pitch ](https://docs.google.com/document/d/1eY9ydHMwopPTqnPlplYmQO62Xwzxh4BBGUJWBqMqTp8/edit)
