### ISSUE TITLE
Create slides to present top tasks results at June MC

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#364]
Dan plans to take about 5 minutes at the June MC to quickly give an update on the top tasks performance testing study. I'm providing the slides and possibly a draft of the script.

**Comment by jaclinec** [comment]
[Draft of slides](https://docs.google.com/presentation/d/1-Sx4UZl8xhtrLQd6XE3LZYHlL7y4G0vGdZNXczsCXFw/edit?usp=sharing)

**Comment by jaclinec** [comment]
[Draft of script](https://docs.google.com/document/d/17bZ8KQE244T7E8QieXekekg69lsKQ-XaO_ty3BJ8qK4/edit?usp=sharing). Both drafts are done and ready for @thisisdano to take and edit as he sees fit for the monthly call.

**Comment by thisisdano** [comment]
Thank you!
