### ISSUE TITLE
Create Github issues for top task findings/recommendations

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#365]
There were many findings and recommendations that came out of the[ top tasks performance testing study](https://docs.google.com/document/d/1snexeKkagu5isGupYIEICzPOVcYhXXnkfIT2vBMQs7E/edit?usp=sharing), and those need to be documented in issues so we can take action on them.

**Comment by jaclinec** [comment]
I've finished creating the issues for top task recommendations:

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-dab52427-7fff-9477-6dc4-748064294982"><div dir="ltr" style="margin-left:0pt;" align="center">
Problem | Recommendation | Github issue
-- | -- | --
Users don’t know the USWDS name for some components and can’t find them with our search | Implement better synonym searching in component search | [#2724](https://github.com/uswds/uswds-site/issues/2724)
Design kit links are buried on the page and hard to find | Make design kit links stand out so they’re easier to find. | [#2723](https://github.com/uswds/uswds-site/issues/2723)
Users can’t find the entire showcase list of sites that use USWDS | Provide a “Show all” link near the showcase list on the homepage that takes users to the entire list of sites that use USWDS. | [#2725](https://github.com/uswds/uswds-site/issues/2725)
The names of the step indicator and in-page navigation didn’t match user expectations, making it difficult to find those components. | Change the names of the step indicator and in-page navigation components to better match user expectations. | [#2728](https://github.com/uswds/uswds-site/issues/2728)
Users tried to find form-related components, like step indicator, in the form component itself but were unable to access it there. | Link to form-related components from the form component page. | [#2729](https://github.com/uswds/uswds-site/issues/2729)
It’s difficult for users to distinguish the hierarchy of left navigation items. | Indent subgroups in the left navigation. | [#2730](https://github.com/uswds/uswds-site/issues/2730)
Some users think the “References” section is the end of the page, so they miss the content below. | Consider putting “References” at the very bottom of the component page (see data visualizations page). | [#2732](https://github.com/uswds/uswds-site/issues/2732)
Legibility is difficult, particularly for Arabic, with white text on a dark background for the language selector. | Make the language selector preview have dark text with white background. | Will discuss at CS/UX sync before creating an issue
Users expect to be able to click on the icons on the homepage but instead must click the link for components, patterns, etc. | Make the icons above the components, patterns, templates, etc. on the homepage clickable. | [#2734](https://github.com/uswds/uswds-site/issues/2734)
Participants often didn’t know the names for components, but they did know what they should look like visually. | Offer component previews on the components page. | [#2736](https://github.com/uswds/uswds-site/issues/2736)
Users often didn't know how USWDS defines heading labels on the site and what they can expect to find in each category. | Provide a glossary of definitions of heading level content (patterns, components etc.) | First we need to create a [glossary component (see proposal discussion](https://github.com/uswds/uswds/discussions/5771)). Then we can address adding it to USWDS site.
Users were overwhelmed by the long showcase list of sites, and felt more context about the sites and their usage of USWDS would make the showcase  more useful. | Provide more context around showcase sites that use USWDS. | [#2737](https://github.com/uswds/uswds-site/issues/2737)
Users had trouble navigating the site to find specific information because the way we have organized and/or labeled content doesn't always match how user expectations. | Consider how we might reorganize the information architecture to better match users’ mental models of how information should be grouped and found. (Roadmap level) | [#2738](https://github.com/uswds/uswds-site/issues/2738)

**Comment by annepetersen** [comment]
Thanks Jacline!
