### ISSUE TITLE
Create Touchpoints survey to send to Web Components working group (tooling)

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#373]
The team decided we needed to learn which tools the Web Components working group has access to / is allowed to use so we can better plan the working group meetings. For instance, we'd like to be able to use Mural but are unsure if everyone can use it. 

We'll create a brief Touchpoints survey to send to the group to see what tools they can use.

**Comment by jaclinec** [comment]
Finished creating the survey and it is published: https://touchpoints.app.cloud.gov/touchpoints/686f0fcc/submit

Dan included a link to that survey in the email sent out to the WC working group.

**Comment by brunerae** [comment]
This survey is complete.
