### ISSUE TITLE
Operationalize Usability Research: Update process documentation

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#376]
We aim to update and publish our usability testing process in the Github wiki. This issue is for capturing the work of creating, reviewing, and approving final content/copy.

**Comment by jaclinec** [comment]
Drafted the public version of our usability testing workflow/process. It will involve publishing 2 more resources that are linked from the process doc, which I already made public versions of as well. Here are the 3 docs:

- [Usability testing process](https://docs.google.com/document/d/1tGou3x0muAuzqK7Qp9ddQ8AcKZs4FT_nMNAcZRGLshk/edit?usp=sharing)
- [Recruitment outreach procedure](https://docs.google.com/document/d/1SUDJLmPC7ujmRB2i5zccz7Po_0wOya72kwXCiYJpMjw/edit?usp=sharing)
- [ Accessibility-first usability testing best practices](https://docs.google.com/document/d/1XoH70m88o1PI40t5Log4hVsMcSMC1Gb_deUZgdvAWVs/edit?usp=sharing)

**Comment by finekatie** [comment]
Hi @jaclinec ! I spent a lot of time with the [process doc](https://docs.google.com/document/d/1tGou3x0muAuzqK7Qp9ddQ8AcKZs4FT_nMNAcZRGLshk). I may have broken it, or I may have presented it in a new light. As always, take what you like and leave the rest :)

**Comment by JaymeCharles** [comment]
Just finished my review of all three docs and left suggestions using track changes.

**Comment by jaclinec** [comment]
@annepetersen all 3 of these docs are all ready for FFR. Thanks!

[Usability testing process](https://docs.google.com/document/d/1tGou3x0muAuzqK7Qp9ddQ8AcKZs4FT_nMNAcZRGLshk/edit?usp=sharing)
[Recruitment outreach procedure](https://docs.google.com/document/d/1SUDJLmPC7ujmRB2i5zccz7Po_0wOya72kwXCiYJpMjw/edit?usp=sharing)
[Accessibility-first usability testing best practices](https://docs.google.com/document/d/1XoH70m88o1PI40t5Log4hVsMcSMC1Gb_deUZgdvAWVs/edit?usp=sharing)

**Comment by finekatie** [comment]
Just following up to note my work is done.

**Comment by annepetersen** [comment]
My review of one of the three of these is complete

**Comment by annepetersen** [comment]
Second complete

**Comment by brunerae** [comment]
@jaclinec / @finekatie - I moved this back to `In Progress` to address Anne's requested changes. Note: Anne is still reviewing [Accessibility-first usability testing best practices](https://docs.google.com/document/d/1XoH70m88o1PI40t5Log4hVsMcSMC1Gb_deUZgdvAWVs/edit?usp=sharing)

**Comment by annepetersen** [comment]
First pass of [Accessibility-first usability testing best practices](https://docs.google.com/document/d/1XoH70m88o1PI40t5Log4hVsMcSMC1Gb_deUZgdvAWVs/edit?usp=sharing) but I requested a lot of changes there

**Comment by jaclinec** [comment]
Anne and I met and they made more changes to the doc (which I accepted) - there is one more comment in there to resolve but otherwise this is ready for FFR.

**Comment by annepetersen** [comment]
Comment resolved and approved: [accessibility-first usability testing best practices](https://docs.google.com/document/d/1XoH70m88o1PI40t5Log4hVsMcSMC1Gb_deUZgdvAWVs/edit?tab=t.0) is done now, which is the last one. All three approved; feel free to post!
