### ISSUE TITLE
Update performance metrics to include most recent data

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#38]
Update the `To check` tab. 
- [x] Add two additional data sources
- [x] Update data from site scanner

**Comment by afeijoo** [comment]
@jAigret-Bix I updated the data sources. There are 300+ sites for us to review. Let's review at our next 9 am daily check-in.

**Comment by afeijoo** [comment]
Data sources added. Next step will be to QA automated data and rerun the site scanner data from Spotlight.
