### ISSUE TITLE
Build and publish Web Components survey in Touchpoints

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#380]
Building on #375 - Create the actual survey tool in Touchpoints. This is for gauging govt digital team structures, tooling, and technical skills that will help inform Web Components work.

**Comment by jaclinec** [comment]
I've built the survey and the preview is ready: https://touchpoints.app.cloud.gov/touchpoints/753a68b3/submit

**Comment by jaclinec** [comment]
Copied screenshots of the survey into a doc since there are some issues with some folks not being able to log in to see the preview. Here's the doc: https://docs.google.com/document/d/1Fkw4jLsszOsue4EgZCGLVUyoDXVUEVNJ-rJRtveC3kI/edit?usp=sharing

Anne has already reviewed and I incorporated their feedback / made updates to the survey. Ready for @thisisdano to review.

**Comment by jaclinec** [comment]
The survey is published: https://touchpoints.app.cloud.gov/touchpoints/753a68b3/submit

**Comment by thisisdano** [comment]
Done
