### ISSUE TITLE
Create research plan for WC interviews

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#381]
### Background 

USWDS is developing  [Web Components](https://docs.google.com/document/d/1exZtf3Hn4XDw8aytJVtUi2dnhJ5SWxfBtdXVn7CG3S4/edit?usp=sharing) and the team has many outstanding questions that, if answered, could help us ensure we build solutions that work for the USWDS community. We are answering some of those questions with other research methods, such as a [Web Component Landscape Analysis](https://docs.google.com/document/d/1eD4TTifCM19cWScRT7wWTlupHmfzZFA4SgSxViqdyaM/edit?usp=sharinghttps://docs.google.com/document/d/1eD4TTifCM19cWScRT7wWTlupHmfzZFA4SgSxViqdyaM/edit?usp=sharing), a Web Component Working Group, and eventual usability testing on beta Web Components. However, there are some questions that are better answered by discussions with potential users. 

This issue is for documenting the research plan for these Web Component interviews.

### Research goals

1. Web Components lessons learned: Discover how other teams have gone about implementing Web Components and what important considerations there may be.
2. Resilience and performance: Learn more about performance of Web Components, resilience needs, and ‘stress’ cases that Web Components need to be able to support.
3. Distribution and installation: Discover optimal ways to distribute and allow installation of Web Components, according to user needs.
4. Customizability: Learn what people expect and need when it comes to customizability of Web Components.

**Comment by jaclinec** [comment]
Draft of [Research plan and script](https://docs.google.com/document/d/1TfazYqqrLgQFaNnNlsDF5ZFY1kwsyGFxvswbl_bMR48/edit?usp=sharing)

**Comment by jaclinec** [comment]
@annepetersen @thisisdano @heymatthenry @amyleadem @mejiaj  - This plan is ready for a subject matter expert's review - hoping to get reviews from at least 2 of you. 

I am particularly needing your feedback on the "Discussion Guide" section (starting on page 4), which is basically the "script" and the actual questions we will be asking the participants. I want to make sure we're asking the right things the right way. **Need your review by EOD Tuesday, Aug 27.**

**Comment by thisisdano** [comment]
Done
