### ISSUE TITLE
Web Components: Conduct interviews

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#383]
Conduct interviews of relevant stakeholders and people with experience in Web Components and web performance. See [research plan](https://docs.google.com/document/d/1TfazYqqrLgQFaNnNlsDF5ZFY1kwsyGFxvswbl_bMR48/edit?usp=sharing) for details.

**Comment by jaclinec** [comment]
We've talked to a few folks already and plan to schedule more sessions over the next few weeks. Other work (WC landscape analysis, govt teams and tools survey) is taking priority right now.

**Comment by jaclinec** [comment]
We've conducted 8 interviews so far. We hope to speak with a few more people (particularly about edge stress cases govt agencies have experienced and system resilience required) so this is still in progress.

**Comment by jaclinec** [comment]
I think the direction we decided to go in was to shift to finding case studies and scenarios published online. If we see particular cases we'd like to follow-up with, we'll potentially reach out and schedule meetings with those folks. But this round of interviews can largely be considered "done." Moving to FFR.

**Comment by thisisdano** [comment]
Done!
