### ISSUE TITLE
September 2024 Newsletter

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds-team#389]
### Helpful links:
Sept newsletter draft here
[Newsletter folder in Google Drive](https://drive.google.com/drive/folders/1xq1tcxcV5hZxNA-6_PH8pycQkkbrCXJ6)
[GovDelivery](https://admin.govdelivery.com/session/new)

### Steps to send newsletter

**Draft copy**
- [x] New release/compile -
- [x] New USWDS sites -
- [x] Accessibility feature -
- [x] Featured component discussions
- [x] August monthly call recap
- [x] September monthly call info
- [x] Section about Web components?
- [x] Survey?

**Review**
- [x]  Review by content team
- [x] Review and feedback from larger team if needed
- [x] FFR - Approval by Anne and Dan

**Compile**
- [x]  Add content to GovDelivery
- [x] Proofread
- [x]  Publish

**Comment by JaymeCharles** [comment]
- Amy and Alex are waiting for Anne's feedback on drafts of the accessibility discussion. Will hopefully have by end of week. 
- [PBGC.gov](http://pbgc.gov/) added to new site feature

**Comment by JaymeCharles** [comment]
- added August MC recap (still need GitHub Q&A discussion link)
- added Accessibility discussion

Blockers: Event brief approval, event page and registration from DG, Compile release info, v3.9 info or Web Components beta

**Comment by finekatie** [comment]
Newsletter was approved today. Scheduled for publish on 9/17 at 3pm
