### ISSUE TITLE
FY24 Q4 Web Governance Policy Review 

### ISSUE THREAD

**Issue by finekatie** [uswds/uswds-team#391]
The new TTS web content review policy requires all TTS website managers to:

- Review the content covered under the policy
- Identify necessary updates
- Work with their team to make those updates - [use the Google sheet](https://docs.google.com/spreadsheets/d/1KPPHXr5YhV2Zyl-c9fZh6NB-kKgXyzgBZyIhio-97OA) for updates and comments
- Complete the [Quarterly TTS web content review form](https://docs.google.com/forms/d/e/1FAIpQLSeN2Yfwqz9bG5dRIJ2i0ZxEhWF0wSdfs-KkdYb7t4cSY6ZJ0w/viewform) to validate that you have completed your review.

**Note:** This version of the policy only applies to targeted content areas. See the policy outline for more on the types of content that are and are not covered.

For additional information on the policy, see the [deck presented to the TTS Digital Council](https://docs.google.com/presentation/d/1H5wO0KoWqYAKfrgmNoUDNA8vUjRzT3eyE4ctuy1G-pw/edit#slide=id.g1ee04787bec_0_315) on January 8, 2024.

**Comment by finekatie** [comment]
Hey @brunerae , I created a ticket for the TTS review. Add or take out anything that needs updating. I can't remember off top of my head when this is due, so if you have that, feel free to enter!

**Comment by finekatie** [comment]
Hey @brunerae should I assign this back to you?

**Comment by annepetersen** [comment]
Due date is in the form: end of day October 15, 2024

**Comment by brunerae** [comment]
Turned over to @annepetersen for FFR on 10/8.

**Comment by brunerae** [comment]
Anne submitted 10/15
