### ISSUE TITLE
Get re-familiarized with existing research on contribution models

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#393]
As we start to work on new contribution model work (see early Sep notes at [CS UX sync](https://docs.google.com/document/d/1IAs5HfPXmD3zWRVB5H_ia2HHXMb5yt-gUqJiUectGWQ/edit?usp=sharing) and [UX a11y sync](https://docs.google.com/document/d/1RufwYve0yuQZ9LhmkVMsMSEHnJjg6RKvyBWjyPA5icE/edit?usp=sharing)), we should first review the research that has already been done. 

- Amy L’s [component lifecycle research](https://docs.google.com/document/d/1IPhwX6TddofuPpzvKV4XxbxJpNt0erLUYKxDNshYAyE/edit#heading=h.fa3sv1ray42g)
- [Contributions to design system](https://medium.com/eightshapes-llc/contributions-to-design-systems-89261a9363d8)
- [Research plan for contribution model](https://docs.google.com/document/d/1xrpll3glNyMf1DGOJEoCJY6ueLROfBCG17pBG3WrP-M/edit#heading=h.6rur7t5za9px) that Elisa worked on: [synthesis deck](https://docs.google.com/presentation/d/1Ajk1_EHDaiAWmZO3L68RSXz-Zx0WPlk0zMLEbdhcbMQ/edit#slide=id.g122255847fe_0_92)
- Article: [Fixing Design System Contribution](https://bencallahan.com/fixing-design-system-contribution)

**Comment by amycole501** [comment]
I reviewed the links in the issue along with a few more resources I found in the "references" section on one of the articles. My notes and takeaways are here https://docs.google.com/document/d/1znV7QzAryrLYa0l782VlSjFxZfrymrkkpUhq_7pnO3s/edit?usp=sharing

**Comment by jaclinec** [comment]
I've finished reviewing all the resources and added my notes/takeaways to the doc as well. I also linked to the initial desk research I started for [Gauging the health of open source projects](https://docs.google.com/document/d/1kZs11_xbLqlHIxjCKbmxt3FvUa4WCYU7Z1dtVZEjUZU/edit?usp=sharing).
