### ISSUE TITLE
Analyze and synthesize WC interview data

### ISSUE THREAD

**Issue by jaclinec** [uswds/uswds-team#401]
We've completed 8 Web Components interviews and may do more, but it's in a place where we can analyze the data and see what we're learning so far. Any further interviews we do can be added to the learnings/findings later.

**Comment by jaclinec** [comment]
I'm compiling themed data from interviews in this [WC Interview Analysis document](https://docs.google.com/document/d/1uEsBm0u-MKCeAXISgv0nTn99aeVBdemyJOMXbW_fKP4/edit?usp=sharing). After documenting all the "raw" data under the categories, I'll further synthesize/distill the data into key insights that I'll create a report for and share with the team when it's ready.

**Comment by jaclinec** [comment]
The focus for the findings report will be to serve as a publicly available reference document outlining decisions we have made related to the Web Components work, and reasons/evidence for those decisions. 

I'll need to gather the decisions we've made so far (related to the topics we covered in the interviews), list them out, and list the supporting evidence for those decisions. I'll likely gather what I can on my own and bring this to CS UX sync to crowdsource the 'decision list' from the team.

**Comment by jaclinec** [comment]
Documenting findings this [WC Interview Key Findings document](https://docs.google.com/document/d/1LGl9DzreHOJaehiDAoI41hXL56XE-LIvy9VMnDu1XQQ/edit?usp=sharing) :lock:

I am working on recommendations and still need to fill out some other basic sections (like background, method, etc.)

**Comment by jaclinec** [comment]
I've finished working on the findings document and it's ready for fed final review.

Important note: The "Recommendations" section is intentionally left undeveloped because I plan to co-create that section with the team in our next CS UX sync. After I get team feedback, I'll come back and finish writing the recommendations.

**Comment by thisisdano** [comment]
Done!
