### ISSUE TITLE
September monthly call activities(9.17)

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#41]
September monthly call (9.17)

*USWDS 2.9.0*
Improvements:
Added align-self utilities
Added accent-warm buttons
Added SHA-256 hash to zip release

*Bug fixes*
Disabled radio button styling
Secondary button active state
List alignment inside alerts
Proper styling of legends

*Three new components*
Identifier
Step indicator
Time Picker

Website updates:
USWDS fundamentals and getting started guide
Sample contract language for 21st century IDEA

Tasks:
- [x] Pre activities: [script submission and review](Monthly call [Script](https://docs.google.com/document/d/17VQ_eZqtsjBocjBTny7hFtSMN-OZBow63YTRrW_3PNc/edit#))
- [NA] possible re-record test
- [x] Prep // run through meeting
- [x] Post call sync
**Post call activities**
- [x] Release announcement
- [x] develop [post call recap announcement](https://docs.google.com/document/d/1LdLHnLmfev0e2MKlTOTmCxvY-y3b_Ypor9Rr6UysSJQ/edit) in gDoc template for review
- [x] Share out call recap  [#uswds-public](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1600979186013200).

* Resource: Identifier [Research Plan](https://docs.google.com/document/d/105f8sFTEHsYWSbO_KVxBXyr2EIX35OISruSID-qs8g4/edit?usp=sharing)

**Comment by thisisdano** [comment]
Call completed.
