### ISSUE TITLE
Plan accessibility and research wiki

### ISSUE THREAD

**Issue by amycole501** [uswds/uswds-team#411]
The UX research and a11y team members will meet to discuss, plan, and ultimately present a process and place to house accessibility and research resources. Some questions and items to include are:

- where will the content be housed?
- will it be discoverable?
- will it have tracking?
- what content will be included? (structure)
- how will it be updated
- when will it be updated
- will we incorporate community guidelines
- assign roles

**Comment by annepetersen** [comment]
Tracking's not possible as far as I know for GitHub wikis

**Comment by brunerae** [comment]
Closing in favor of #421
