### ISSUE TITLE
Analyze USWDS monthly call data

### ISSUE THREAD

**Issue by afeijoo** [uswds/uswds-team#42]
Over time, how many RSVPs are from repeat vs. first time-registrants?

[Goal](https://docs.google.com/spreadsheets/d/1I-mvcAIBE7QFpMBg_S4llLqalkbUWDMFHkhOH19pCms/edit?ts=5f57d21f#gid=0): Increase the number of first-time registrants.

**Comment by afeijoo** [comment]
@RhettSkelton Can you please pull the monthly registration data from FY 2020 into a gSheet?

**Comment by RhettSkelton** [comment]
Data with analysis is available here: https://docs.google.com/spreadsheets/d/1-vak7wqVLFodbWun_yW-YAAST8PHxW7XYmFTlQNqerA/edit#gid=1968314679

**Comment by afeijoo** [comment]
Done - we identified a few new strategies that we'll use to [promote the October monthly call](https://docs.google.com/document/d/1DbTDJ_d2fBXR6jX2OwxcUY2RhRzfIO5LvuT61QjfYAc/edit#):lock:.
