### ISSUE TITLE
Deprecate components.designsystem.digital.gov

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#45]
Tasks to deprecate https://components.designsystem.digital.gov:

- [x] JA - [Inventory and crosswalk ](https://docs.google.com/spreadsheets/d/1rM1JkbL-RGwE3DRXhvD7fYpogZ-yYHLh9Wt8DBAQc4k/edit#gid=0)the components on `components.designsystem.digital.gov` to confirm they're on `designsystem.digital.gov/components`
- [x] JA -[Create issues](https://github.com/uswds/uswds/issues/3736) to add any missing components to the USWDS site
- [x] JM - Remove [all links to the components subdomain](https://github.com/uswds/uswds-site/search?q=%22components.designsystem.digital.gov%22) from `uswds-site`
- [x] AFF - Submit an issue in https://github.com/18F/dns/issues and ask them set up a 301 redirect from `components.designsystem.digital.gov` to `designsystem.digital.gov/components`
- [x] AFF - Update https://github.com/uswds/uswds-team/issues/7, the issue that tracks our modernization punchlist, to mark this item as complete
- [x] AFF - Update the [GSA website inventory](https://docs.google.com/spreadsheets/d/1OBO6g7_OsVBv0vG8WSCI6L2FD_iRh3A7a_6eQWj2zLE/edit#gid=2013137748) to list `components` as a redirect

**Comment by jAigret-Bix** [comment]
@afeijoo  @mejiaj has removed all links to the components subdomain from uswds-site

**Comment by afeijoo** [comment]
@jAigret-Bix I submitted the request for the 301 redirect: https://github.com/18F/dns/issues/482.

**Comment by afeijoo** [comment]
Done. https://components.designsystem.digital.gov now redirects to https://designsystem.digital.gov/components

https://github.com/18F/pages-redirects/pull/170 and https://github.com/18F/dns/pull/495
