### ISSUE TITLE
Sample contract language: comms plan and approval

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#48]
Create a communication plan for Sample contract language. Review and approval of plan. 
[Draft Comms messaging](https://docs.google.com/document/d/1XHwzQC-Zjf9KjfA12aX9eaZq4lWSira-LJKln9FLDIs/edit)
Plan should include: 
- [x] Create short post to cross promote on Digital.gov and in the Digital.gov newsletter
- [x] Draft email and share with web managers listserv
- [x] Draft Slack message and share on #uswds-public Slack
- [x] Draft social promos and tweet from USWDS and Digital.gov

**DoD**
- [x] USWDS review and approval
- [x] Comms review and approval 2/3
- [x] follow up w execution of comms plan #60

**Comment by katieekline** [comment]
@afeijoo and @thisisdano The [comms](https://docs.google.com/document/d/1XHwzQC-Zjf9KjfA12aX9eaZq4lWSira-LJKln9FLDIs/edit?usp=sharing) for the contract language page is ready for your review.

**Comment by afeijoo** [comment]
Reviewed and routed for comms approval. Marked as `blocked` pending their approval.
