### ISSUE TITLE
November monthly call (11/19) and activities

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#50]
- [x] Monthly call prep meeting 11/2
- [x] Pre activities: [script submission and review]
- [x] Prep // run through meeting
- [x] Monthly call 11/19
- [x]  Post call sync 11/19
- [x] Create [post-call draft](https://docs.google.com/document/d/1ffFG2hH1-tqwLsNWMgIwCNqyrXTGkGCQK47sdFT6HcE/edit#heading=h.4n0ubsygsk65) gDoc template for review and approval **NLT 11/23
- [x] Create [draft slack post ](https://gsa-tts.slack.com/files/T025AQGAN/F01GHL40108?origin_team=T025AQGAN)announcement
- [x] Add video chapter points into update when video is posted https://www.youtube.com/watch?v=r0H6CiP-FN0
- [x]  Share out call recap [#uswds-public](https://gsa-tts.slack.com/files/T025AQGAN/F01GHL40108?origin_team=T025AQGAN).

**Comment by afeijoo** [comment]
✅ I reviewed the [post-call recap](https://docs.google.com/document/d/1ffFG2hH1-tqwLsNWMgIwCNqyrXTGkGCQK47sdFT6HcE/edit#heading=h.4n0ubsygsk65).

**Comment by katieekline** [comment]
The [draft post](https://gsa-tts.slack.com/files/T025AQGAN/F01GHL40108?origin_team=T025AQGAN) was sent to @thisisdano for review.
