### ISSUE TITLE
Tree Test and TryMyUI

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#55]
Base line of current state of find-ability of USWDS.
- [x] [Draft Research Plan](https://docs.google.com/document/d/1cxgaz4WmHsre-AVLymfJYUlT3gYcdRC19M9DLFTCoG0/edit) 
- [x] Run tests TryMyUI and TreeTest
- [x] [Share results w team](https://drive.google.com/file/d/1laqjrITA4uqCHvzWrTcfnKXxCMOgKkYb/view?usp=sharing)

**DOD**
- [x] Make findings and results available to @katieekline and new UX team members for further strategic consideration. Findings and summary are located [here](https://drive.google.com/drive/folders/1-jn2-bSL9rLdGHb_u2gkh4ok3gsYCYUc?usp=sharing)

**Comment by allie-shaw** [comment]
Baseline feedback for USWDS site.
Scenario
"You are working at a company that is planning on redesigning their company website. The company is considering incorporating a design system into the new website."

1. Your supervisor has asked you to research about the principles and guidelines of USWDS. Where would you go find that information?
2. You've been tasked to start research on how to adopt USWDS. Where would you go to find out this information?
3. You've been tasked to create an example or prototype of   how your site would look using USWDS. Where would you go to find out how to create one?
4. You've been tasked to install USWDS. Where would you go to   obtain instructions on how to install?
5. You've installed USWDS and need to change the color and   fonts to match your branding. Where would you go to find out how to do these tasks?
6. You're having issues with your installation. Where would you go for help?
7. You'd like to find out more about the header and footer components. Where would you look?
8. You'd like to look at examples of how USWDS components can be used. Where would you look?
