### ISSUE TITLE
Coordinate meeting with HHS/ASPA

### ISSUE THREAD

**Issue by KimberlyHodges** [uswds/uswds-team#6]
scheduling internal meeting with Bixal and Dan and Ammie to discuss approach for meeting with ASPA product owner to discuss USWDS adoption

**Comment by thisisdano** [comment]
We did this.

**Comment by nks-bix** [comment]
[Notes on HHS/ASPA approach to strategy](https://drive.google.com/open?id=1KAf-CAos5yywOF18Ax0rA4WCFEOfy9fn)
