### ISSUE TITLE
Comms execution: Valentines day

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#61]
[Comms plan](https://drive.google.com/file/d/1QibISHseliiD6g52K7_EOJlnteos2NM4/view?usp=sharing) and designs located in this [folder ](https://drive.google.com/drive/folders/1aFmUfT7uTGuZu8EhMNtA13b5dMgRqHys?usp=sharing)

- [x] draft comms plan, review and approval #59 
- [x] create and publish blog page to site https://github.com/uswds/uswds-site/issues/1147
- [x] Meet w Rhett to determine and assign responsibilities (2/4)
- [x] Execute plan

**DoD**
- [x] [Comms plan](https://docs.google.com/document/d/1QibISHseliiD6g52K7_EOJlnteos2NM4/edit#heading=h.5hptrad07hw) is complete

**Comment by jAigret-Bix** [comment]
V-day Comms execution is complete. Issue will be closed by JA 2/17

**Comment by afeijoo** [comment]
Accepted.
