### ISSUE TITLE
Onboard new team members

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#63]
- [x] on-board new members
- [x] complete new member [punch list](https://docs.google.com/spreadsheets/d/1heUmWmHot6dF8NcJsrPJmdOZC6xZnzDvxJEH4F8Y3So/edit#gid=1370094768)

**DOD**
- [x] all punch list items are complete for KC, SS, SQ, KM

**Comment by jAigret-Bix** [comment]
[ punch list ](https://docs.google.com/spreadsheets/d/1heUmWmHot6dF8NcJsrPJmdOZC6xZnzDvxJEH4F8Y3So/edit#gid=1370094768)items are complete for KC, SS, SQ, KM. issue is ready for acceptance @afeijoo

**Comment by afeijoo** [comment]
🎉 4 down, 1 to go!

**Comment by afeijoo** [comment]
@jAigret-Bix Can you pls. add a new issue for Jeff?
