### ISSUE TITLE
March 18: monthly call prep and follow up

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#68]
- [x] Monthly call prep meeting 
- [x] create polling questions 
- [x] script submission and review
 - [x] Prep // run through: tech check (as needed)
- [x]  Monthly call 
- [x]  Post call sync 
- [x]  Create post-call slack recap draft
- [x]  Add video chapter points into update when video is posted
- [x]  Chat transcript [QA compile ](https://docs.google.com/spreadsheets/d/1pzL3bTLDpSZdEbae9hAuMX5Izh45pPER8AjFx7CF-Jo/edit#gid=1756436669)
- [x]  Share out call [recap](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1616602779010100)

Follow up Issues 
QA answer and share out: https://github.com/uswds/uswds/issues/4124 
External link guidance: https://github.com/uswds/uswds/issues/4125

**Comment by KMullan944** [comment]
Monthly Call recap summary here: 
https://docs.google.com/document/d/1yR5OqjNaCGDUfE7FBj1rblJHSwN5yTkcaYjRRbPUb-Y/edit 

Posted to slack 3/24/21

**Comment by jAigret-Bix** [comment]
March call activities complete, follow up issues created for additional tasks: 
QA answer and share out: uswds/uswds#4124
External link guidance: uswds/uswds#4125
this issue is ready for acceptance @afeijoo
