### ISSUE TITLE
Comms campaign 2101

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#77]
CAMPAIGN 2101

- [x] create comms plan -- use template messaging
- [x] develop graphics
- [x] execute comms plan

**Comment by jAigret-Bix** [comment]
@afeijoo #govpossible campaign creation and execution is complete. issue is ready for acceptance.

**Comment by afeijoo** [comment]
Sent all messages except the 3 for the Pgov blog post, which I'll send after it is published.
