### ISSUE TITLE
May MC follow up activities

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#81]
- [x] [Comms follow up](https://docs.google.com/document/d/18XdVfW1orXCMQFLghYMCxPoi0BKTAJBTeEc7sd-s7Uo/edit#heading=h.p3hvn8jllvv2) as described 5/21 (KM)
- [x] Customer list update (JA)

**Comment by KMullan944** [comment]
Starting progress here: https://docs.google.com/document/d/18XdVfW1orXCMQFLghYMCxPoi0BKTAJBTeEc7sd-s7Uo/edit#
