### ISSUE TITLE
Comms: Mini-campaign 2021-03

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#83]
- [x]  Draft comms plan
- [x] Execute comms plan

**Comment by KMullan944** [comment]
This is approved and ready to go by Ammie. Part 2 is around 4th of July so I think we are good to go with this! Just need to execute on it

**Comment by jAigret-Bix** [comment]
The comms campaign is executed. Issue is ready for acceptance @afeijoo
