### ISSUE TITLE
June MC outreach follow up

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#85]
June MC outreach and engagement  follow up

**Comment by KMullan944** [comment]
https://docs.google.com/document/d/1yg3xBEg6HSs0aX0_YMemnUlBOV07_PjOa2YBqcUtl-A/edit#

**Comment by KMullan944** [comment]
^^ latest working doc for these comms

**Comment by jAigret-Bix** [comment]
https://gsa-tts.slack.com/archives/C3F14AHSQ/p1625151314021800 Complete and closing issue
