### ISSUE TITLE
Impact Story

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#86]
Create and deliver Impact Story

Description and [Template](https://docs.google.com/document/d/1z06HZvBD_UyTSFHFAftSzmR0LjqFCrZ5d0MoDZ4eUs0/edit#heading=h.axz7yjaaqcw6): 

- [x] Create [draft impact story](https://docs.google.com/document/d/1ghiVSh0u49apNtahyhXedA-P50CZn00zcPO9IsguT8M/edit) for review by EOD 7/22 (KK)
- [x] Review w DW and make updates (shared w DW 2/23)
- [x] Acceptance (DW)
- [x] Target due date: 7/23

DoD
- [x] All tasks complete

**Comment by thisisdano** [comment]
Done
