### ISSUE TITLE
Monthly Call: Aug 19

### ISSUE THREAD

**Issue by jAigret-Bix** [uswds/uswds-team#89]
See production schedule https://docs.google.com/document/d/1vuGyX3f7LsCBKCgjzZKtwJG6CD3cwVrpDRksWv--QOo/edit#heading=h.rgzild6ukx76

[Draft recap post](https://docs.google.com/document/d/1scDLzoFrUP3wRkNCbBwfhHcPsSlcjHj8KyM18Qk1e_M/edit?usp=sharing)

**Comment by jAigret-Bix** [comment]
August call and [recap post](https://gsa-tts.slack.com/archives/C3F14AHSQ/p1629747243102000) complete. Issue is ready for acceptance

**Comment by jAigret-Bix** [comment]
@thisisdano Call and post recap is complete. Issue can be closed.

**Comment by thisisdano** [comment]
Done!
