### ISSUE TITLE
Transition documentation

### ISSUE THREAD

**Issue by nks-bix** [uswds/uswds-team#9]

**Comment by nks-bix** [comment]
[Transition doc](https://drive.google.com/open?id=13ouU2RbdSBurk80Fjeg28jhtPkV-7xui)

**Comment by KimberlyHodges** [comment]
@nks-bix @afeijoo I made a couple of comments on the transition plan if you could take a look at them. I'm open to discuss further if you'd like.

**Comment by afeijoo** [comment]
@nks-bix I cannot edit the document to resolve the comments. I reviewed and agree with your notes. Can you please resolve them? 

After you resolve them, I'll move this from `Fed Final Review` to `Done`.

**Comment by nks-bix** [comment]
done! thank you.
